# Generated by Django 4.2.4 on 2023-09-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_customuser_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10)),
                ('shop_name', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('selling_preference', models.CharField(max_length=50)),
                ('shipping_fee_preference', models.CharField(max_length=50)),
                ('local_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('national_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
