# Generated by Django 4.2.4 on 2023-09-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_sellerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerdetails',
            old_name='user',
            new_name='seller',
        ),
    ]
