# Generated by Django 4.2.4 on 2023-09-14 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_user_sellerdetails_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerdetails',
            options={'verbose_name_plural': 'SellerDetails'},
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='local_charges',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='national_charges',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='regional_charges',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='selling_preference',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='shipping_fee_preference',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='street',
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='account_holder_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_details_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='branch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
