# Generated by Django 4.2.4 on 2023-09-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_sellerdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='pan_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
