# Generated by Django 4.2.4 on 2023-09-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_sellerdetails_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdetails',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
