# Generated by Django 4.2.4 on 2023-09-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_sellerdetails_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='building_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
