# Generated by Django 4.2.4 on 2023-10-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
