# Generated by Django 5.0.1 on 2024-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hub_status',
            field=models.BooleanField(default=False),
        ),
    ]
