# Generated by Django 5.0.1 on 2024-02-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_customuser_hub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_agent',
            field=models.BooleanField(default=False),
        ),
    ]
