# Generated by Django 4.2.4 on 2023-10-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Logout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
