# Generated by Django 4.2.4 on 2023-09-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0002_customer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_profile',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
