# Generated by Django 4.2.4 on 2023-10-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0002_site_logout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_Logout',
            new_name='Site_Logo',
        ),
    ]
