# Generated by Django 4.2.4 on 2023-09-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0003_rename_customer_id_customer_profile_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
