# Generated by Django 4.2.4 on 2023-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0003_rename_site_logout_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('deactivated', 'Deactivated'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
