# Generated by Django 4.2.4 on 2023-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0006_remove_products_price_seedproduct_cropproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seedproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
