# Generated by Django 4.2.4 on 2023-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0007_cropproduct_stock_seedproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedproduct',
            name='price_100gm',
        ),
        migrations.RemoveField(
            model_name='seedproduct',
            name='price_150gm',
        ),
        migrations.RemoveField(
            model_name='seedproduct',
            name='weight_option_150gm',
        ),
        migrations.AddField(
            model_name='seedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cropproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
