# Generated by Django 4.2.4 on 2023-10-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0008_uploadedimage_remove_shippingaddress_building_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
