# Generated by Django 4.2.4 on 2023-09-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0008_remove_seedproduct_price_100gm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedproduct',
            name='weight_option_100gm',
        ),
    ]
