# Generated by Django 4.2.4 on 2023-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0009_remove_seedproduct_weight_option_100gm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropproduct',
            name='product_category',
        ),
        migrations.AddField(
            model_name='seedproduct',
            name='product_subcategory',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cropproduct',
            name='product_subcategory',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
