# Generated by Django 4.2.4 on 2023-09-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0012_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedproduct',
            name='seller',
        ),
        migrations.DeleteModel(
            name='CropProduct',
        ),
        migrations.DeleteModel(
            name='SeedProduct',
        ),
    ]
