# Generated by Django 4.2.4 on 2024-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0015_product_average_rating_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
