# Generated by Django 4.2.4 on 2024-01-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0016_remove_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
