# Generated by Django 4.2.4 on 2023-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0017_alter_customer_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
