# Generated by Django 5.0.1 on 2024-01-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0017_customerreview_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growbag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('drainage_holes', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
