# Generated by Django 5.0.1 on 2024-02-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0018_growbag_notification_ordernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Growbag',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
