# Generated by Django 4.2.4 on 2023-09-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0018_alter_customer_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='home', max_length=10),
        ),
    ]
