# Generated by Django 5.0.1 on 2024-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0020_growbag_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growbag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='growbag',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='growbag',
            name='material',
        ),
        migrations.RemoveField(
            model_name='growbag',
            name='size',
        ),
        migrations.AddField(
            model_name='growbag',
            name='color_chosen',
            field=models.CharField(blank=True, choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='growbag',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='growbag',
            name='icon_chosen',
            field=models.CharField(blank=True, choices=[('sun', 'Sun'), ('leaf', 'Leaf'), ('water', 'Water Droplet'), ('globe', 'Globe'), ('heart', 'Heart'), ('tree', 'Tree'), ('moon', 'Moon'), ('plant', 'Seedling'), ('vegetable', 'Carrot'), ('fruit', 'Apple'), ('crops', 'Wheat'), ('cannabis', 'Cannabis')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='growbag',
            name='size_chosen',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('regular', 'Regular')], max_length=255, null=True),
        ),
    ]
