# Generated by Django 4.2.4 on 2023-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0020_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_items',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
