# Generated by Django 4.2.4 on 2023-09-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0021_cartitem_total_items_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
