# Generated by Django 5.0.1 on 2024-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0021_remove_growbag_color_remove_growbag_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growbag',
            name='color_chosen',
            field=models.CharField(choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple')], default='brown', max_length=255),
        ),
        migrations.AlterField(
            model_name='growbag',
            name='size_chosen',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('regular', 'Regular')], default='regular', max_length=255),
        ),
    ]
