# Generated by Django 5.0.1 on 2024-02-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0022_alter_growbag_color_chosen_alter_growbag_size_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growbag',
            name='drainage_holes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
