# Generated by Django 5.0.1 on 2024-02-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0023_alter_growbag_drainage_holes'),
    ]

    operations = [
        migrations.AddField(
            model_name='growbag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='growbag_images/'),
        ),
        migrations.AddField(
            model_name='growbag',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='growbag',
            name='color_chosen',
            field=models.CharField(choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('violet', 'Violet'), ('red', 'Red'), ('purple', 'Purple')], default='brown', max_length=255),
        ),
        migrations.AlterField(
            model_name='growbag',
            name='icon_chosen',
            field=models.CharField(blank=True, choices=[('sun', 'Sun'), ('leaf', 'Leaf'), ('water', 'Water'), ('globe', 'Globe'), ('heart', 'Heart'), ('tree', 'Tree'), ('moon', 'Moon'), ('plant', 'Plant'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('crops', 'Crops'), ('cannabis', 'Cannabis')], max_length=255, null=True),
        ),
    ]
