# Generated by Django 5.0.1 on 2024-02-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0024_growbag_image_growbag_qty_alter_growbag_color_chosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], default='spring', max_length=20),
        ),
    ]
