# Generated by Django 4.2.4 on 2023-09-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0024_order_payment_status_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
