# Generated by Django 5.0.1 on 2024-02-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0025_product_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ManyToManyField(blank=True, related_name='products', to='agriselect.season'),
        ),
    ]
