# Generated by Django 4.2.4 on 2023-09-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0025_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
