# Generated by Django 4.2.4 on 2023-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0026_remove_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='agriselect.cartitem'),
        ),
    ]
