# Generated by Django 5.0.1 on 2024-02-20 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0027_sellerrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_only',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
