# Generated by Django 4.2.4 on 2023-10-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0029_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
    ]
