# Generated by Django 5.0.1 on 2024-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0029_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='selected_season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], default='summer', max_length=20),
        ),
    ]
