# Generated by Django 5.0.1 on 2024-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0030_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Requested', max_length=20),
        ),
    ]
