# Generated by Django 5.0.1 on 2024-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0032_cartitem_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='accepted_by_store',
            field=models.BooleanField(default=False),
        ),
    ]
