# Generated by Django 5.0.1 on 2024-02-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0033_cartitem_accepted_by_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by_store',
            field=models.BooleanField(default=False),
        ),
    ]
