# Generated by Django 4.2.4 on 2023-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0033_remove_order_products_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='agriselect.product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
