# Generated by Django 5.0.1 on 2024-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0035_deliveryagentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagentprofile',
            old_name='id_number',
            new_name='aadhaar_number',
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='employee_id',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
