# Generated by Django 5.0.1 on 2024-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0037_deliveryagentprofile_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
