# Generated by Django 5.0.1 on 2024-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0039_alter_deliveryagentprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='aadhaar_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='driver_license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
