# Generated by Django 5.0.1 on 2024-03-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0041_address_nearest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='nearest_location',
        ),
    ]
