# Generated by Django 5.0.1 on 2024-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0043_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Malappuram', 'Malappuram'), ('Pathanamthitta', 'Pathanamthitta'), ('Kannur', 'Kannur')], max_length=100, null=True),
        ),
    ]
