# Generated by Django 5.0.1 on 2024-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0044_address_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='location',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur')], max_length=100),
        ),
    ]
