# Generated by Django 5.0.1 on 2024-03-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0050_cartitem_ready_for_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
