# Generated by Django 5.0 on 2024-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0051_customer_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='otp',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
