# Generated by Django 5.0 on 2024-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0052_customer_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
