# Generated by Django 5.0 on 2024-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0053_order_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
