# Generated by Django 5.0 on 2024-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0055_deliveryagentprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='latitude_zip',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='longitude_zip',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
