# Generated by Django 5.0 on 2024-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0057_assigneddeliveryagent_useragentdistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
