# Generated by Django 5.0 on 2024-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0058_deliveryagentprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='latitude_zip',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='longitude_zip',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
