# Generated by Django 5.0 on 2024-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0059_customer_profile_latitude_zip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='latitude_zip',
        ),
        migrations.RemoveField(
            model_name='customer_profile',
            name='longitude_zip',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude_zip',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude_zip',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
