# Generated by Django 5.0 on 2024-03-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0060_remove_customer_profile_latitude_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
