# Generated by Django 5.0 on 2024-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriselect', '0063_growbag_order_date_only_growbag_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growbag',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
